### ISSUE TITLE
Bug: some profiles I stopped to follow on other nostr clients, still appear as I'm following on Plasma

### ISSUE THREAD

**Issue by bitcoinuser** [jmateoac/plasma#275]
Hi,

Bug: some profiles I stopped to follow on other nostr clients, still appear as I'm following on Plasma and I still see their notes on my feed.

Obs. On both clients, the following numbers are equal.

Thanks.

**Comment by bitcoinuser** [comment]
New version today? Please say yes. Haha.

**Comment by jmateoac** [comment]
> New version today? Please say yes. Haha.

I wasn't planning on it, but now I will! 🫡

**Comment by bitcoinuser** [comment]
> > New version today? Please say yes. Haha.
> 
> I wasn't planning on it, but now I will! 🫡

Wow, thanks. I'm loving Plasma. Better have a client with not with many features, but stable and the ones that exist, working.

**Comment by bitcoinuser** [comment]
It's really smooth the feed, I like it. The design is beautifull too.

**Comment by jmateoac** [comment]
> It's really smooth the feed, I like it. The design is beautifull too.

I'm glad you like it! você estaria disposto a me ajudar a traduzir o aplicativo para o português?

**Comment by bitcoinuser** [comment]
> > It's really smooth the feed, I like it. The design is beautifull too.
> 
> I'm glad you like it! você estaria disposto a me ajudar a traduzir o aplicativo para o português?

Yes, I love translate apps. I translated Alby extension and Blockstream Green wallets to Portuguese. One using weblate and other on transifex.
