### ISSUE TITLE
Bug: switch between tabs make the notes information load again

### ISSUE THREAD

**Issue by bitcoinuser** [jmateoac/plasma#297]
Hi,

Bug: switch between tabs make the notes information load again. See the the photo of bitcoin magazine note.

https://github.com/plasma-social/plasma/assets/1178856/7233df7a-dc26-46ba-a0c5-607c457b5cd6

**Comment by bitcoinuser** [comment]
Hi @jmateoac what about this case? not switching tabs but instead scroll up and down.
PR #297 fix it too? thanks.


https://github.com/plasma-social/plasma/assets/1178856/5119cae9-97a7-42f5-80a8-f48ea7a16d7f

**Comment by jmateoac** [comment]
> 

#297 won't fix #174. But this is on my list for the near future!

**Comment by bitcoinuser** [comment]
> Hi @jmateoac what about this case? not switching tabs but instead scroll up and down. PR #297 fix it too? thanks.
> 
>  Screenrecorder-2023-06-19-16-26-25-44.mp4

The problem here is other. I think you didn't understand. Not related to #174

**Comment by jmateoac** [comment]
Oh sorry! I'm on a train with slow wifi, and the video wasn't loading for me 😅 
I'm working on a big update that should fix this and other loading issues, but can you create an issue for it?
